/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.mx.uttt.vistas;

import edu.mx.uttt.recursividad.Recursividad;
import javax.swing.JOptionPane;

/**
 *
 * @author vania
 */
public class RecursividadVista extends javax.swing.JFrame {

    /**
     * Creates new form RecursividadVista
     */
    public RecursividadVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ejercicios = new javax.swing.ButtonGroup();
        Series = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnEnviar = new javax.swing.JButton();
        btnSuma = new javax.swing.JButton();
        btnPotencia = new javax.swing.JButton();
        btnMcd = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        S1 = new javax.swing.JCheckBox();
        S2 = new javax.swing.JCheckBox();
        S3 = new javax.swing.JCheckBox();
        S4 = new javax.swing.JCheckBox();
        btnCalcular = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        E1 = new javax.swing.JCheckBox();
        E2 = new javax.swing.JCheckBox();
        btnCalcular1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Roboto Slab Thin", 1, 48)); // NOI18N
        jLabel1.setText("RECURSIVIDAD");

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));

        btnEnviar.setBackground(new java.awt.Color(255, 255, 204));
        btnEnviar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEnviar.setText("Factorial");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        btnSuma.setBackground(new java.awt.Color(255, 255, 204));
        btnSuma.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSuma.setText("Suma Impares");
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });

        btnPotencia.setBackground(new java.awt.Color(255, 255, 204));
        btnPotencia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPotencia.setText("Potencia");
        btnPotencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPotenciaActionPerformed(evt);
            }
        });

        btnMcd.setBackground(new java.awt.Color(255, 255, 204));
        btnMcd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMcd.setText("MCD");
        btnMcd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMcdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEnviar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnSuma)
                                .addGap(0, 36, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnPotencia)))))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnMcd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnMcd)
                .addGap(18, 18, 18)
                .addComponent(btnEnviar)
                .addGap(18, 18, 18)
                .addComponent(btnSuma)
                .addGap(18, 18, 18)
                .addComponent(btnPotencia)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 153));

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel3.setText("SERIES");

        S1.setBackground(new java.awt.Color(255, 255, 204));
        Series.add(S1);
        S1.setSelected(true);
        S1.setText("Serie 1");

        S2.setBackground(new java.awt.Color(255, 255, 204));
        Series.add(S2);
        S2.setText("Serie 2");

        S3.setBackground(new java.awt.Color(255, 255, 204));
        Series.add(S3);
        S3.setText("Serie 3");

        S4.setBackground(new java.awt.Color(255, 255, 204));
        Series.add(S4);
        S4.setText("Serie 4");

        btnCalcular.setBackground(new java.awt.Color(255, 255, 204));
        btnCalcular.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(S2)
                            .addComponent(S1)
                            .addComponent(S3)
                            .addComponent(S4)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(S1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(S2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(S3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(S4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCalcular)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 153));

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel2.setText("EJERCICIOS");

        E1.setBackground(new java.awt.Color(255, 255, 204));
        Ejercicios.add(E1);
        E1.setSelected(true);
        E1.setText("Ejercicio 1");

        E2.setBackground(new java.awt.Color(255, 255, 204));
        Ejercicios.add(E2);
        E2.setText("Ejercicio 2");

        btnCalcular1.setBackground(new java.awt.Color(255, 255, 204));
        btnCalcular1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCalcular1.setText("Calcular");
        btnCalcular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcular1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(btnCalcular1)
                    .addComponent(E2)
                    .addComponent(E1))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(E1)
                .addGap(32, 32, 32)
                .addComponent(E2)
                .addGap(27, 27, 27)
                .addComponent(btnCalcular1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        if (S1.isSelected()) {
            String x = JOptionPane.showInputDialog("Introduce las veces que se repetirá la serie.");
            if (isNumber(x)) {
                int n = Integer.parseInt(x);
                JOptionPane.showMessageDialog(null, "El resultado es: " +Recursividad.serie1(n));
            }
        } else if (S2.isSelected()) {
            String x = JOptionPane.showInputDialog("Introduce el multiplicando");
            String y = JOptionPane.showInputDialog("Introduce el multiplicador");
            if (isNumber(x) && isNumber(y)) {
                int n = Integer.parseInt(x);
                int m = Integer.parseInt(y);
                Recursividad.serie2(n, m);
            }
        } else if (S3.isSelected()) {
            String x = JOptionPane.showInputDialog("Introduce las veces que se repetirá la serie.");
            if (isNumber(x)) {
                int n = Integer.parseInt(x);
                double v = 3.0;
                double c = 1.0;
                double y = 3.0;
                int i = 1;
                JOptionPane.showMessageDialog(null, "El resultado es: " + Recursividad.serie3(n, y, v, c, i));
            }
        } else if (S4.isSelected()) {
            String x = JOptionPane.showInputDialog("Introduce las veces que se repetirá la serie.");
            if (isNumber(x)) {
                double i=1;
                int n = Integer.parseInt(x);
                JOptionPane.showMessageDialog(null, "Resultado: " + Recursividad.serieDivision2(n,i));
            }
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
        String x = JOptionPane.showInputDialog("Introduce el numero a factorizar");
        if (isNumber(x)) {
            int n = Integer.parseInt(x);
            JOptionPane.showMessageDialog(null, "Resultado: "+Recursividad.factorialRecursividad(n));
        }
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
        // TODO add your handling code here:
        String x = JOptionPane.showInputDialog("Introduce el multiplicando");
            String y = JOptionPane.showInputDialog("Introduce el multiplicador");
            if (isNumber(x) && isNumber(y)) {
                int n = Integer.parseInt(x);
                int m = Integer.parseInt(y);
                JOptionPane.showMessageDialog(null, "Resultado: "+Recursividad.sumaImparRecursivo(n, m));
            }
    }//GEN-LAST:event_btnSumaActionPerformed

    private void btnMcdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMcdActionPerformed
        // TODO add your handling code here:
        String x = JOptionPane.showInputDialog("Introduce el divisor");
        String y = JOptionPane.showInputDialog("Introduce el dividendo");
        if (isNumber(x) && isNumber(y)) {
            int n = Integer.parseInt(x);
            int m = Integer.parseInt(y);
            JOptionPane.showMessageDialog(null, "MCD: "+Recursividad.mcd(n, m));
        }
    }//GEN-LAST:event_btnMcdActionPerformed

    private void btnPotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPotenciaActionPerformed
        // TODO add your handling code here:
        String b = JOptionPane.showInputDialog("Coloca la base de la potencia: ");
        String n = JOptionPane.showInputDialog("Coloca el exponente de la potencia: ");
        if(isNumber(b) && isNumber(n)){
            int base = Integer.parseInt(b);
            int exponente = Integer.parseInt(n);
            JOptionPane.showMessageDialog(null, "Resultado: "+Recursividad.potencia(base, exponente));
        }
    }//GEN-LAST:event_btnPotenciaActionPerformed

    private void btnCalcular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcular1ActionPerformed
        // TODO add your handling code here:
        if(E1.isSelected()){
            String x = JOptionPane.showInputDialog("Introduce el numero de veces a repetir la serie");
        if (isNumber(x)) {
            int n = Integer.parseInt(x);
             JOptionPane.showMessageDialog(null, "Resultado: "+Recursividad.ejercicio1(n));
        }
        }else{
            String x = JOptionPane.showInputDialog("Introduce el numero de calificaciones");
        if (isNumber(x)) {
            int n = Integer.parseInt(x);
            JOptionPane.showMessageDialog(null, "Promedio: "+Recursividad.calcularEjercicio2(n));
        }
        }
    }//GEN-LAST:event_btnCalcular1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    private boolean isNumber(String cadena) {
        try {
            Integer.parseInt(cadena);
            return true;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingresa un número válido. Error: " + e.getMessage());
            return false;
        }
    }

    private boolean isNumberD(String cadena) {
        try {
            Double.parseDouble(cadena);
            return true;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingresa un número válido. Error: " + e.getMessage());
            return false;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox E1;
    private javax.swing.JCheckBox E2;
    private javax.swing.ButtonGroup Ejercicios;
    private javax.swing.JCheckBox S1;
    private javax.swing.JCheckBox S2;
    private javax.swing.JCheckBox S3;
    private javax.swing.JCheckBox S4;
    private javax.swing.ButtonGroup Series;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnCalcular1;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnMcd;
    private javax.swing.JButton btnPotencia;
    private javax.swing.JButton btnSuma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
