/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.mx.uttt.vistas;

import edu.mx.uttt.arreglos.Operaciones;
    
/**
 *
 * @author vania
 */
public class OrdenarVectores extends javax.swing.JFrame {
    VistaArreglos vistaArreglos = new VistaArreglos();
    //Operaciones ope = new Operaciones();
    Operaciones operaciones; 
        
    /**
     * Creates new form OrdenarVectores
     */
    public OrdenarVectores(Operaciones operaciones) {
        this.operaciones = operaciones;
        initComponents();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ordenamiento = new javax.swing.ButtonGroup();
        tipo = new javax.swing.ButtonGroup();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        tipoO = new javax.swing.JPanel();
        btnBurbuja = new javax.swing.JCheckBox();
        btnBurbujaMejorada = new javax.swing.JCheckBox();
        btnShell = new javax.swing.JCheckBox();
        btnMerge = new javax.swing.JCheckBox();
        btnQuick = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        btnAsc = new javax.swing.JCheckBox();
        btnDesc = new javax.swing.JCheckBox();
        txtImprimir = new javax.swing.JTextField();
        btnOrdenar = new javax.swing.JButton();

        jTextField2.setText("jTextField1");

        jTextField3.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));

        tipoO.setBackground(new java.awt.Color(255, 255, 255));
        tipoO.setToolTipText("Tipo de Ordenamiento");

        ordenamiento.add(btnBurbuja);
        btnBurbuja.setSelected(true);
        btnBurbuja.setText("Burbuja");

        ordenamiento.add(btnBurbujaMejorada);
        btnBurbujaMejorada.setText("BurbujaMejorada");

        ordenamiento.add(btnShell);
        btnShell.setText("Shell");

        ordenamiento.add(btnMerge);
        btnMerge.setText("Merge");

        ordenamiento.add(btnQuick);
        btnQuick.setText("Quick sort");

        javax.swing.GroupLayout tipoOLayout = new javax.swing.GroupLayout(tipoO);
        tipoO.setLayout(tipoOLayout);
        tipoOLayout.setHorizontalGroup(
            tipoOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tipoOLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBurbuja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(btnBurbujaMejorada)
                .addGap(40, 40, 40)
                .addComponent(btnQuick)
                .addGap(40, 40, 40))
            .addGroup(tipoOLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(btnShell)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMerge)
                .addGap(105, 105, 105))
        );
        tipoOLayout.setVerticalGroup(
            tipoOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tipoOLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tipoOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBurbuja)
                    .addComponent(btnBurbujaMejorada)
                    .addComponent(btnQuick))
                .addGap(18, 18, 18)
                .addGroup(tipoOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnShell)
                    .addComponent(btnMerge))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setToolTipText("123");

        tipo.add(btnAsc);
        btnAsc.setSelected(true);
        btnAsc.setText("Ascendente");

        tipo.add(btnDesc);
        btnDesc.setText("Descendente");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAsc)
                .addGap(30, 30, 30)
                .addComponent(btnDesc))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAsc)
                    .addComponent(btnDesc))
                .addContainerGap())
        );

        btnOrdenar.setText("Ordenar");
        btnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtImprimir, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tipoO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOrdenar)
                        .addGap(36, 36, 36)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(tipoO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnOrdenar)))
                .addGap(25, 25, 25)
                .addComponent(txtImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed
        // TODO add your handling code here:
        
        if(btnBurbuja.isSelected()){
            if(btnAsc.isSelected()){
                operaciones.ordenarAsc();
                txtImprimir.setText(operaciones.imprimirOrdenado());
            }else{
                operaciones.ordenarDesc();
                txtImprimir.setText(operaciones.imprimirOrdenado());
            }
        }if(btnBurbujaMejorada.isSelected()){
            if(btnAsc.isSelected()){
                operaciones.burbujaMejorada();
                txtImprimir.setText(operaciones.imprimirOrdenado());
            }else{
                operaciones.burbujaMejoradaDesc();
                txtImprimir.setText(operaciones.imprimirOrdenado());
            }
        }if(btnQuick.isSelected()){
            if(btnAsc.isSelected()){
                operaciones.ordenamientoQuickSort(0, (operaciones.getArreglo().length-1));
                txtImprimir.setText(operaciones.imprimirOrdenado());
            }else{
                operaciones.ordenamientoQuickSortDesc(0, (operaciones.getArreglo().length-1));
                txtImprimir.setText(operaciones.imprimirOrdenado());
            }
        }if(btnShell.isSelected()){
            if(btnAsc.isSelected()){
                operaciones.ordenamientoShell();
                txtImprimir.setText(operaciones.imprimirOrdenado());
            }else{
                operaciones.ordenamientoShellDesc();
                txtImprimir.setText(operaciones.imprimirOrdenado());
            }
        }if(btnMerge.isSelected()){
            if(btnAsc.isSelected()){
                operaciones.ordenamientoMerge(operaciones.getArreglo());
                txtImprimir.setText(operaciones.imprimirOrdenado());
            }else{
                operaciones.ordenamientoMergeDesc(operaciones.getArreglo());
                txtImprimir.setText(operaciones.imprimirOrdenado());
            }
        }
    }//GEN-LAST:event_btnOrdenarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox btnAsc;
    private javax.swing.JCheckBox btnBurbuja;
    private javax.swing.JCheckBox btnBurbujaMejorada;
    private javax.swing.JCheckBox btnDesc;
    private javax.swing.JCheckBox btnMerge;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JCheckBox btnQuick;
    private javax.swing.JCheckBox btnShell;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.ButtonGroup ordenamiento;
    private javax.swing.ButtonGroup tipo;
    private javax.swing.JPanel tipoO;
    private javax.swing.JTextField txtImprimir;
    // End of variables declaration//GEN-END:variables
}
