/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.mx.uttt.arreglos;
import edu.mx.uttt.arreglos.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author vania
 */
public class Vista extends javax.swing.JFrame {
    Operaciones operacion = null;
    Operaciones operacion2 = null;
    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        txtSumaValores.setEditable(false);
        txtNumeroMaximo.setEditable(false);
        btnBuscarValor.setEnabled(false);
        txtBuscarValor.setEnabled(false);
        txtTotalPrimos.setEditable(false);
        btnSumaVectores.setEnabled(false);
        btnSumarValores.setEnabled(false);
        btnNumeroMayor.setEnabled(false);
        btnTotalPrimos.setEnabled(false);
        txtTotalPares.setEnabled(false);
        btnCopiar.setEnabled(false);
        txtDesc.setEditable(false);
        txtAsc.setEditable(false);
        btnDesc.setEnabled(false);
        btnAsc.setEnabled(false);
        txtVector2.setEditable(false);
        txtImprimir.setEditable(false);
        btnLlenar.setEnabled(false);
        btnImprimir.setEnabled(false);
        btnTotalPares.setEnabled(false);
        btnLimpiar.setEnabled(false);
        txtSumaVectores.setEnabled(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTamanio = new javax.swing.JTextField();
        txtSumaValores = new javax.swing.JTextField();
        txtTotalPrimos = new javax.swing.JTextField();
        txtNumeroMaximo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTotalPares = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtBuscarValor = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnCrear = new javax.swing.JButton();
        btnLlenar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnSumarValores = new javax.swing.JButton();
        btnNumeroMayor = new javax.swing.JButton();
        btnTotalPrimos = new javax.swing.JButton();
        btnTotalPares = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnSumaVectores = new javax.swing.JButton();
        btnBuscarValor = new javax.swing.JButton();
        btnAsc = new javax.swing.JButton();
        btnDesc = new javax.swing.JButton();
        btnCopiar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtImprimir = new javax.swing.JTextField();
        txtSumaVectores = new javax.swing.JTextField();
        txtVector2 = new javax.swing.JTextField();
        txtAsc = new javax.swing.JTextField();
        txtDesc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 0));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        txtTamanio.setText("3");

        txtSumaValores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSumaValoresActionPerformed(evt);
            }
        });

        txtTotalPrimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalPrimosActionPerformed(evt);
            }
        });

        jLabel1.setText("Tamaño");

        jLabel2.setText("Suma Valores");

        jLabel3.setText("Total Números Primos");

        jLabel4.setText("Número Máximo");

        jLabel6.setText("Total Números Pares");

        jLabel7.setText("¿Valor Encontrado?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(66, 66, 66)
                        .addComponent(txtTamanio, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBuscarValor, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtNumeroMaximo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                .addComponent(txtTotalPrimos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                .addComponent(txtSumaValores, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                .addComponent(txtTotalPares, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(22, 22, 22))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTamanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSumaValores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTotalPrimos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNumeroMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTotalPares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(26, 26, 26))
        );

        jPanel2.setBackground(new java.awt.Color(204, 153, 255));

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnLlenar.setText("Llenar");
        btnLlenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLlenarActionPerformed(evt);
            }
        });

        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        btnSumarValores.setText("Sumar Valores");
        btnSumarValores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumarValoresActionPerformed(evt);
            }
        });

        btnNumeroMayor.setText("Número Mayor");
        btnNumeroMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumeroMayorActionPerformed(evt);
            }
        });

        btnTotalPrimos.setText("Total Números Primos");
        btnTotalPrimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalPrimosActionPerformed(evt);
            }
        });

        btnTotalPares.setText("Total Números Pares");
        btnTotalPares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalParesActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar Valores");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnSumaVectores.setText("Sumar Vectores");
        btnSumaVectores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaVectoresActionPerformed(evt);
            }
        });

        btnBuscarValor.setText("Buscar Valor en Vector");
        btnBuscarValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarValorActionPerformed(evt);
            }
        });

        btnAsc.setText("Ascendente");
        btnAsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAscActionPerformed(evt);
            }
        });

        btnDesc.setText("Descendente");
        btnDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescActionPerformed(evt);
            }
        });

        btnCopiar.setText("Copiar Vector");
        btnCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnCrear)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnLlenar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnImprimir))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnNumeroMayor)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSumarValores))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnTotalPrimos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSumaVectores))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBuscarValor)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(btnTotalPares)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAsc)
                            .addComponent(btnCopiar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDesc)
                            .addComponent(btnLimpiar))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLlenar)
                    .addComponent(btnCrear)
                    .addComponent(btnImprimir))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnSumarValores))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNumeroMayor)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSumaVectores)
                    .addComponent(btnTotalPrimos))
                .addGap(13, 13, 13)
                .addComponent(btnTotalPares)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarValor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDesc)
                    .addComponent(btnCopiar))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnAsc))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 153, 255));

        txtImprimir.setText("Vector Ingresado: ");

        txtSumaVectores.setText("Suma de Vectores:");

        txtVector2.setText("Vector 2: ");

        txtAsc.setText("Ascendente: ");

        txtDesc.setText("Descendente: ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtVector2)
                    .addComponent(txtImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSumaVectores)
                    .addComponent(txtAsc)
                    .addComponent(txtDesc))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtSumaVectores, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAsc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVector2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(67, 67, 67))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
        txtSumaValores.setText("");
        txtNumeroMaximo.setText("");
        txtTotalPrimos.setText("");
        txtSumaVectores.setText("Suma de Vectores: ");
        txtImprimir.setText("Vector Ingresados: ");
        txtAsc.setText("Ascendente: ");
        txtDesc.setText("Descendente: ");
        txtTotalPares.setText("");
        txtBuscarValor.setText("");
        if(isNumber(txtTamanio.getText())){
        btnLlenar.setEnabled(true);
        operacion = new Operaciones(Integer.parseInt(txtTamanio.getText()));
        operacion2 = new Operaciones(Integer.parseInt(txtTamanio.getText()));
        }else{
            jLabel5.setText("Los valores ingresados no son válidos");
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void txtTotalPrimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalPrimosActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtTotalPrimosActionPerformed

    private void txtSumaValoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSumaValoresActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtSumaValoresActionPerformed

    private void btnLlenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLlenarActionPerformed
        // TODO add your handling code here:
        btnSumarValores.setEnabled(true);
        btnNumeroMayor.setEnabled(true);
        btnTotalPrimos.setEnabled(true);
        btnImprimir.setEnabled(true);
        btnSumaVectores.setEnabled(true);
        btnTotalPares.setEnabled(true);
        btnLimpiar.setEnabled(true);
        btnBuscarValor.setEnabled(true);
        btnCopiar.setEnabled(true);
        btnDesc.setEnabled(true);
        btnAsc.setEnabled(true);
        operacion.llenarArreglo();
        operacion2.llenarArreglo2(operacion2.getArreglo());
    }//GEN-LAST:event_btnLlenarActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
        txtImprimir.setText(operacion.imprimir());
        txtVector2.setText(operacion.imprimirArreglo2(operacion2.getArreglo()));
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnNumeroMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumeroMayorActionPerformed
        // TODO add your handling code here:
        txtNumeroMaximo.setText(Integer.toString(operacion.numeroMayor()));
    }//GEN-LAST:event_btnNumeroMayorActionPerformed

    private void btnTotalPrimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalPrimosActionPerformed
        // TODO add your handling code here:
        txtTotalPrimos.setText(Integer.toString(operacion.numerosPrimos()));
    }//GEN-LAST:event_btnTotalPrimosActionPerformed

    private void btnSumarValoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumarValoresActionPerformed
        // TODO add your handling code here:
        txtSumaValores.setText(Integer.toString(operacion.sumaValores()));
    }//GEN-LAST:event_btnSumarValoresActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnTotalParesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalParesActionPerformed
        // TODO add your handling code here:
        txtTotalPares.setText(Integer.toString(operacion.numerosPares()));
    }//GEN-LAST:event_btnTotalParesActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        txtSumaValores.setText("");
        txtNumeroMaximo.setText("");
        txtTotalPrimos.setText("");
        txtImprimir.setText("");
        txtTotalPares.setText("");
        txtBuscarValor.setText("");
        txtSumaVectores.setText("Suma de Vectores: ");
        txtImprimir.setText("Vector Ingresado: ");
        txtVector2.setText("Vector 2: ");
        txtAsc.setText("Ascendente: ");
        txtDesc.setText("Descendente: ");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSumaVectoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaVectoresActionPerformed
        // TODO add your handling code here:
        txtSumaVectores.setText(operacion.imprimirArreglo(operacion2.getArreglo()));
    }//GEN-LAST:event_btnSumaVectoresActionPerformed

    private void btnBuscarValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarValorActionPerformed
        // TODO add your handling code here:
        txtBuscarValor.setText(operacion.buscarValor(operacion.getArreglo()));
    }//GEN-LAST:event_btnBuscarValorActionPerformed

    private void btnAscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAscActionPerformed
        // TODO add your handling code here:
        operacion.ordenarAsc();
        txtAsc.setText(operacion.imprimirBurbuja());
    }//GEN-LAST:event_btnAscActionPerformed

    private void btnDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescActionPerformed
        // TODO add your handling code here:
        operacion.ordenarDesc();
        txtDesc.setText(operacion.imprimirBurbuja());
    }//GEN-LAST:event_btnDescActionPerformed

    private void btnCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopiarActionPerformed
        // TODO add your handling code here:
        txtVector2.setText(operacion.copiarVector(operacion2.getArreglo()));
        
    }//GEN-LAST:event_btnCopiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }
    private static boolean isNumber(String cadena){
        try{
            Integer.parseInt(cadena);
            return true;
        }catch(NumberFormatException ex){
            return false;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsc;
    private javax.swing.JButton btnBuscarValor;
    private javax.swing.JButton btnCopiar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnDesc;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnLlenar;
    private javax.swing.JButton btnNumeroMayor;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSumaVectores;
    private javax.swing.JButton btnSumarValores;
    private javax.swing.JButton btnTotalPares;
    private javax.swing.JButton btnTotalPrimos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtAsc;
    private javax.swing.JTextField txtBuscarValor;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtImprimir;
    private javax.swing.JTextField txtNumeroMaximo;
    private javax.swing.JTextField txtSumaValores;
    private javax.swing.JTextField txtSumaVectores;
    private javax.swing.JTextField txtTamanio;
    private javax.swing.JTextField txtTotalPares;
    private javax.swing.JTextField txtTotalPrimos;
    private javax.swing.JTextField txtVector2;
    // End of variables declaration//GEN-END:variables
}
